#!/bin/bash
#
# Install git-annex. Any environment setup to source would be
# written to ${HOME}/dlinstaller_env.sh
#
set -e -u

# no install requested -> exit
[ -z "$1" ] && exit 0 || true

# assumes a virtualenv or equivalent python env
# get the installer for this
python -m pip install datalad-installer${DATALAD_INSTALLER_VERSION:-}
datalad-installer -E ${HOME}/dlinstaller_env.sh --sudo ok $*
