#!/bin/bash

set -e

# no install requested -> exit
[ -z "$1" ] && exit 0 || true

if (which apt-get > /dev/null ); then
	sudo apt-get update -qq -y --allow-releaseinfo-change
	sudo apt-get install -q --no-install-recommends -y eatmydata
	sudo eatmydata apt-get install -q --no-install-recommends -y $*
else
	brew install -q $*
fi
