Basic concepts
--------------

What is this about...

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/philosophy
   intro/datasets
   intro/Howto

Use cases
---------

Hands-on real-world applications with step-by-step recipes...

.. toctree::
   :maxdepth: 1

   usecases/REMoDNaV

Misc
----

.. toctree::
   :maxdepth: 1

   glossary

.. note::
   Notes defined within all diatonic and chromatic musical scales have been
   intentionally excluded from this list of additional notes. Additionally,
   this note.
