.. only:: html

    .. figure:: artwork/src/enter.svg
       :width: 60%

################
**Introduction**
################

.. toctree::
   :hidden:

   intro/user_types

.. toctree::
   :maxdepth: 1
   :caption: What DataLad and the handbook are all about

   intro/philosophy
   intro/narrative
   intro/installation
   intro/howto
   intro/executive_summary

.. only:: html

   .. figure:: artwork/src/basics.svg
      :width: 60%
      :target: http://handbook.datalad.org/en/latest/basics/intro.html

##########
**Basics**
##########

.. toctree::
   :hidden:

   basics/intro.rst

.. toctree::
   :maxdepth: 2
   :caption: Learn all about DataLad

   basics/basics-datasets
   basics/basics-run
   basics/basics-annex
   basics/basics-collaboration
   basics/basics-configuration
   basics/basics-yoda
   basics/basics-containers
   basics/basics-thirdparty
   basics/basics-help

.. only:: html

   .. figure:: artwork/src/advanced.svg
      :width: 60%
      :target: http://handbook.datalad.org/en/latest/beyond_basics/intro.html

############
**Advanced**
############


.. toctree::
   :hidden:

   beyond_basics/intro.rst

.. toctree::
   :maxdepth: 2
   :caption: Beyond the Basics

   beyond_basics/basics-advancedoptions
   beyond_basics/basics-scaling

.. only:: html

   .. figure:: artwork/src/usecases.svg
      :width: 60%
      :target: http://handbook.datalad.org/en/latest/usecases/intro.html

#############
**Use cases**
#############

.. toctree::
   :hidden:

   usecases/intro

.. toctree::
   :maxdepth: 1
   :numbered:
   :caption: Hands-on real-world applications with step-by-step recipes...

   usecases/collaborative_data_management
   usecases/provenance_tracking
   usecases/reproducible-paper
   usecases/supervision
   usecases/reproducible_neuroimaging_analysis
   usecases/HCP_dataset
   usecases/datastorage_for_institutions
   usecases/extending_data_ecosystem


########
Appendix
########

.. toctree::
   :maxdepth: 1
   :caption: Further information and references

   glossary
   basics/101-180-FAQ
   basics/101-136-cheatsheet
   contributing
   teaching
   acknowledgements


########################
Code lists from chapters
########################

.. toctree::
   :maxdepth: 1
   :caption: Easy access to copy-paste snippets for workshops

   code_from_chapters/intro
   code_from_chapters/01_dataset_basics_code
   code_from_chapters/02_reproducible_execution_code
   code_from_chapters/10_yoda_code

* :ref:`genindex`
* :ref:`search`

..
  stuff that we do not need or show at the moment

.. only:: adminmode

    .. toctree::
       :hidden:

       usecases/datasets