name: Handbook build
on: [push]
jobs:
  bookbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up environment
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
          sudo apt-get update
          sudo apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk librsvg2-bin
      - name: Build docs
        run: |
          make doctest
          make html
          make latexpdf

